# start the docker container: docker-compose -f docker-compose-local.yml up
version: '3.6'

services:
  db:
    image: postgres:9.3
    ports:
      - "5432:5432"
    env_file:
      - .env_db_pgsql

  adminer:
    image: adminer
    ports:
      - "5080:8080"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
      - "443:443"
    links:
      - db:postgres-server
    environment:
      - ZBX_DEBUGLEVEL=3 # increase this to 5 to enable verbose mode

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
     - "8081:80"
     - "8443:443"
    links:
     - db:postgres-server
     - zabbix-server:zabbix-server
